language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.4
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "3.4"
      env: DJANGO_VERSION=1.4
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - (cd tests/end2end && virtualenv env && source ./env/bin/activate && pip install -r requirements.txt && pip install Django==$DJANGO_VERSION && cd ../../ && python setup.py install)
before_script: pep8 .
script:
  - python setup.py test
  - (cd tests/end2end && source ./env/bin/activate && python manage.py test)
